I393 segdtoph5 add option -F for continue mini file from
PIC-IRIS/PH5 pull request #426
Opened 2020-08-07 17:28 UTC by damhuonglan

### What does this PR do?
Issue #393 states that segdtoph5 doesn't continue mini file (miniPH5_xxxxx.ph5) index from option `-S first_mini`. However, that option is to state the first mini file index of all. In segdtoph5 there is no option to continue mini file index from. 

This PR adds option `-F from_mini `to continue index for mini file from, in which the mini files created will not be greater than 100GB and only keep data for one das. This option will not be associated with option `-M num_mini`.
The help in segdtoph5 is modified as following to avoid misleading: 
```

  -M num_mini, --num_mini=num_mini
                        Create a given number of miniPH5 files. Ex: -M 38
  -S first_mini, --first_mini=first_mini
                        The index of the first miniPH5_xxxxx.ph5 file of all.
                        Ex: -S 5
  -F from_mini, --from_mini=from_mini
                        The index to continue miniPH5_xxxxx.ph5 file from. Do
                        not associate with num_mini. Ex: -F 25
```

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

2020-08-18 19:20 UTC, dsentinel commented on ph5/utilities/segd2ph5.py
> +                       metavar="from_mini", type='int', default=None)
metavar isn't necessary for named arguments if setting to the same as the arg name

2020-08-18 19:21 UTC, dsentinel commented on ph5/utilities/segd2ph5.py
> +        raise Exception('Option -O must be associated with option -F.')
Mutual exclusion can be handled by argparse
https://docs.python.org/3/library/argparse.html#mutual-exclusion

2020-08-18 19:23 UTC, dsentinel commented on ph5/utilities/segd2ph5.py
> +                    return 1
what does return 1 mean?

2020-08-25 19:57 UTC, damhuonglan commented
List of checks need to be done:

- [ ] Argument helps and examples make sense

- [ ] -M associate with -F gives error

- [ ] -O without -F gives error

- [ ] -M still works the same as before

- [ ] -F with value less than the highest mini file gives error

- [ ] -F without -O: start mini file from F's value, 1 file can have more than one das's data

- [ ] -F with -O: start mini file from F's value, 1 file can have only one das's data

You can add any more checks that you feel need too.

2020-09-28 16:05 UTC, hrotman-pic reviewed
It looks like the -F option permits adding same DAS to new minis, making it easier to add service runs to an existing archive without having to resubmit the entire archive.  Please see Working/Holly_append_test/PR426/test1.  I have not validated that test archive since that is out of scope.

Overall the help is more informative and makes more sense.  One small suggestion for -M flag, I think it would be good if help said also 'Recommend using when creating a new PH5' since I think that is the intended use of -M.

2020-09-29 14:05 UTC, hrotman-pic commented
To clarify, I have *only* tested segdtoph5 as that was the original scope of this PR and I had a set of comparison test archives.  I recommend additional reviewers for the other ingestion commands.

2020-09-29 21:45 UTC, ascire-pic commented
@hrotman-pic is going to test mstoph5 and 125atoph5
@akram-pic is going to test seg2toph5 and 130toph5

2020-09-29 21:49 UTC, damhuonglan commented
> To clarify, I have _only_ tested segdtoph5 as that was the original scope of this PR and I had a set of comparison test archives. I recommend additional reviewers for the other ingestion commands.

@hrotman-pic Thanks for your review. I already put your recommended help message to -M. I already added -M to other ingestion commands too. 

> @hrotman-pic is going to test mstoph5 and 125atoph5
> @akram-pic is going to test seg2toph5 and 130toph5

All data ingestion commands can be tested in this PR (checkout branch: i393_segdtoph5_optionS) except for mstoph5 is in PR #429 (checkout branch: i393-mstoph5_optionS)

2020-10-14 14:58 UTC, hrotman-pic requested changes
Based on the meeting, this review is requesting:
Removal of -F option for all ingestion commands changed under this PR, so that users cannot recreate the problem of data from one DAS in two or more mini files.

The changes to the help for other options, such as 'Ex: -M 38' are still useful in my view.

I am not sure about keeping 'Recommend using when creating a new PH5' for the -M option help (for all ingestion commands in this PR).  If we keep it, I think it will help if the help for the -M option also says that adding new data to an existing PH5 may not create new mini files.

Going slightly out of the scope of the discussion: I think it would help standalone users to have an example of an ingestion command listed in the help, such as: 
segdtoph5 -n master.ph5 -c 6 -U 18N -M 20
And to state that -S defaults to 1 if not specified in the help for -S option.

2020-10-27 21:08 UTC, damhuonglan commented
replaced with PR#434

2020-10-27 21:08 UTC, closed without merging