Add try catch to ph5avialbility.
PIC-IRIS/PH5 pull request #510
Opened 2022-11-29 20:33 UTC by timronan

Thank your for contributing to PH5

Before submitting a PR, please review the pull request guidelines:
https://github.com/PIC-IRIS/PH5/blob/master/CONTRIBUTING.md#submitting-a-pull-request

### What does this PR do?

### Relevant Issues?

### Checklist
- [ ] This PR is not directly related to an existing issue (which has no PR yet).
- [ ] All tests pass.
- [ ] Any new or changed features have are documented.
- [ ] Changes have been added to `CHANGELOG.txt` .
- [ ] First time contributors have added your name to `CONTRIBUTORS.txt` .

2022-11-29 20:39 UTC, damhuonglan requested changes

2022-11-29 20:39 UTC, damhuonglan commented on ph5/clients/ph5availability.py
> -                            Das_t = das_info[ph5_das][key]
I had a mistake here. Please use `Das_t = das_info[ph5_das][k]`

2022-11-29 20:39 UTC, damhuonglan commented on ph5/clients/ph5availability.py
> -                            das_info[ph5_das][key] = Das_t
Also here `das_info[ph5_das][key] = Das_t`.
Then you wont get KeyError anymore.

2022-12-06 15:26 UTC, damhuonglan commented
@timronan I see that you still didn't finish this branch. I will finish this and ask you to have the final review.

2022-12-06 16:42 UTC, damhuonglan commented
@timronan I fixed the code but can't request you to review it because you are the owner of this PR. Please has a look and leave a comment here. Thank you.

2022-12-06 16:48 UTC, damhuonglan commented
@timronan I fixed the key but can't request you to review because you're the owner of the  PR. Please have a look and leave your review here. Thanks.

2022-12-06 17:42 UTC, timronan commented
Thanks for fixing that. I am merging now.

2022-12-06 17:43 UTC, timronan commented on ph5/clients/ph5availability.py
> -                            Das_t = das_info[ph5_das][key]
Resolved

2022-12-06 17:45 UTC, timronan commented
@damhuonglan Please re-review and resolve the conversation so I can merge it.

2022-12-06 17:56 UTC, damhuonglan approved these changes
It's good to be merged now.

2022-12-06 17:59 UTC, merged